sel0 0 _	sel0  R 0 R
sel0 1 _	sel0  R _ N
sel0 _ _	mate  L _ L
mate 0 0	mate  L 0 N
mate 1 0	mate  L 0 L
mate _ _	fin  R _ N
mate _ 0	few1  N _ N
mate 0 _ 	few0  N _ N
mate 1 _	few0  N _ N
fin 0 _ 	fin  R _ N
fin 1 _ 	fin  R _ N
fin _ _ 	!acpt  N _ N
